openapi: "3.0.1"
info:
  title: API Notes
  version: "1"
  description: |
    Minimal API for upload markdown (with attachments) and render it as HTML.
    The generated link is randomly generated and can be shared relatively safely.

servers:
  - url: /

security:
  - HeaderAuth: [ ]
  - QueryAuth: [ ]
paths:
  /notes:
    post:
      operationId: createNote
      summary: Create new note
      description: |
        Create new note from draft with (optional) attachments.
        Returns public URL and unique ID.
        Consumer should not make any assumptions about ID and treat it as
        arbitrary string with variable reasonable length.
        
        Attachments with name index.html will be ignored.
        Note can use relative reference to attachments as-is.
      requestBody:
        description: Note draft
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/draft"
      responses:
        200:
          description: Note created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/note"

  /note/{id}:
    put:
      operationId: updateNote
      summary: |
        Update existent note by ID. 
        Old attachments may not be removed, but could be replaced.
      parameters:
        - in: path
          name: id
          description: Note ID
          schema:
            type: string
            example: deadbeaf
          required: true
      requestBody:
        description: Note draft
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/draft"
      responses:
        204:
          description: Note updated

    delete:
      operationId: deleteNote
      summary: |
        Remove existent note and all attachments.
      parameters:
        - in: path
          name: id
          description: Note ID
          schema:
            type: string
            example: deadbeaf
          required: true
      responses:
        204:
          description: Note removed

components:
  schemas:
    draft:
      type: object
      properties:
        title:
          type: string
          description: Note title
          example: Hello world!
        text:
          type: string
          description: Note body
          example: This is long text
        author:
          type: string
          description: Optional (and not verifiable) author of note
          example: RedDec
        hide_attachments:
          type: boolean
          default: false
          description: Do not make list of attachments
        attachment:
          type: array
          description: File attachment
          items:
            type: string
            format: binary
      required:
        - title
        - text

    note:
      type: object
      properties:
        id:
          type: string
          description: Unique note ID
          example: deadbeaf
        public_url:
          type: string
          description: Public URL
          example: https://example.com/note/a/b/c/deadbeaf
      required:
        - id
        - public_url

  securitySchemes:
    HeaderAuth:
      type: apiKey
      in: header
      name: X-Api-Key
    QueryAuth:
      type: apiKey
      in: query
      name: token