// Code generated by ogen, DO NOT EDIT.

package client

// setDefaults set default value of fields.
func (s *DraftMultipart) setDefaults() {
	{
		val := bool(false)
		s.HideAttachments.SetTo(val)
	}
}
