// Code generated by ogen, DO NOT EDIT.

package api

// DeleteNoteParams is parameters of deleteNote operation.
type DeleteNoteParams struct {
	// Note ID.
	ID string
}

// UpdateNoteParams is parameters of updateNote operation.
type UpdateNoteParams struct {
	// Note ID.
	ID string
}
