// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateNote implements createNote operation.
//
// Create new note from draft with (optional) attachments.
// Returns public URL and unique ID.
// Consumer should not make any assumptions about ID and treat it as
// arbitrary string with variable reasonable length.
// Attachments with name index.html will be ignored.
// Note can use relative reference to attachments as-is.
//
// POST /notes
func (UnimplementedHandler) CreateNote(ctx context.Context, req *DraftMultipart) (r *Note, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteNote implements deleteNote operation.
//
// Remove existent note and all attachments.
//
// DELETE /note/{id}
func (UnimplementedHandler) DeleteNote(ctx context.Context, params DeleteNoteParams) error {
	return ht.ErrNotImplemented
}

// UpdateNote implements updateNote operation.
//
// Update existent note by ID.
// Old attachments may not be removed, but could be replaced.
//
// PUT /note/{id}
func (UnimplementedHandler) UpdateNote(ctx context.Context, req *DraftMultipart, params UpdateNoteParams) error {
	return ht.ErrNotImplemented
}
