// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateNote implements createNote operation.
	//
	// Create new note.
	//
	// POST /notes
	CreateNote(ctx context.Context, req OptDraftMultipart) (*Note, error)
	// DeleteNote implements deleteNote operation.
	//
	// Remove existent note.
	//
	// DELETE /note/{id}
	DeleteNote(ctx context.Context, params DeleteNoteParams) error
	// UpdateNote implements updateNote operation.
	//
	// Update existent note.
	//
	// PUT /note/{id}
	UpdateNote(ctx context.Context, req OptDraftMultipart, params UpdateNoteParams) error
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
