// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateNote implements createNote operation.
//
// Create new note.
//
// POST /notes
func (UnimplementedHandler) CreateNote(ctx context.Context, req OptDraftMultipart) (r *Note, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteNote implements deleteNote operation.
//
// Remove existent note.
//
// DELETE /note/{id}
func (UnimplementedHandler) DeleteNote(ctx context.Context, params DeleteNoteParams) error {
	return ht.ErrNotImplemented
}

// UpdateNote implements updateNote operation.
//
// Update existent note.
//
// PUT /note/{id}
func (UnimplementedHandler) UpdateNote(ctx context.Context, req OptDraftMultipart, params UpdateNoteParams) error {
	return ht.ErrNotImplemented
}
